/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout.settings'
import { Route as LayoutProxyRouteImport } from './routes/_layout.proxy'
import { Route as LayoutPolicyRouteImport } from './routes/_layout.policy'
import { Route as LayoutKeysRouteImport } from './routes/_layout.keys'
import { Route as LayoutEngineRouteImport } from './routes/_layout.engine'
import { Route as LayoutDashboardRouteImport } from './routes/_layout.dashboard'
import { Route as LayoutConfigRouteImport } from './routes/_layout.config'
import { Route as LayoutAuditRouteImport } from './routes/_layout.audit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProxyRoute = LayoutProxyRouteImport.update({
  id: '/proxy',
  path: '/proxy',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPolicyRoute = LayoutPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKeysRoute = LayoutKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEngineRoute = LayoutEngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConfigRoute = LayoutConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuditRoute = LayoutAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof LayoutAuditRoute
  '/config': typeof LayoutConfigRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/engine': typeof LayoutEngineRoute
  '/keys': typeof LayoutKeysRoute
  '/policy': typeof LayoutPolicyRoute
  '/proxy': typeof LayoutProxyRoute
  '/settings': typeof LayoutSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof LayoutAuditRoute
  '/config': typeof LayoutConfigRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/engine': typeof LayoutEngineRoute
  '/keys': typeof LayoutKeysRoute
  '/policy': typeof LayoutPolicyRoute
  '/proxy': typeof LayoutProxyRoute
  '/settings': typeof LayoutSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/audit': typeof LayoutAuditRoute
  '/_layout/config': typeof LayoutConfigRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/engine': typeof LayoutEngineRoute
  '/_layout/keys': typeof LayoutKeysRoute
  '/_layout/policy': typeof LayoutPolicyRoute
  '/_layout/proxy': typeof LayoutProxyRoute
  '/_layout/settings': typeof LayoutSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/config'
    | '/dashboard'
    | '/engine'
    | '/keys'
    | '/policy'
    | '/proxy'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit'
    | '/config'
    | '/dashboard'
    | '/engine'
    | '/keys'
    | '/policy'
    | '/proxy'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/audit'
    | '/_layout/config'
    | '/_layout/dashboard'
    | '/_layout/engine'
    | '/_layout/keys'
    | '/_layout/policy'
    | '/_layout/proxy'
    | '/_layout/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/proxy': {
      id: '/_layout/proxy'
      path: '/proxy'
      fullPath: '/proxy'
      preLoaderRoute: typeof LayoutProxyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/policy': {
      id: '/_layout/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof LayoutPolicyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/keys': {
      id: '/_layout/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof LayoutKeysRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/engine': {
      id: '/_layout/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof LayoutEngineRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/config': {
      id: '/_layout/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof LayoutConfigRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/audit': {
      id: '/_layout/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof LayoutAuditRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAuditRoute: typeof LayoutAuditRoute
  LayoutConfigRoute: typeof LayoutConfigRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutEngineRoute: typeof LayoutEngineRoute
  LayoutKeysRoute: typeof LayoutKeysRoute
  LayoutPolicyRoute: typeof LayoutPolicyRoute
  LayoutProxyRoute: typeof LayoutProxyRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuditRoute: LayoutAuditRoute,
  LayoutConfigRoute: LayoutConfigRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutEngineRoute: LayoutEngineRoute,
  LayoutKeysRoute: LayoutKeysRoute,
  LayoutPolicyRoute: LayoutPolicyRoute,
  LayoutProxyRoute: LayoutProxyRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
